-- Money Tracker — таблица транзакций, RLS, тестовые данные
-- Применить:
--   1. Supabase Studio → SQL Editor → New query → вставить файл → Run
--      ИЛИ
--   2. supabase db push   (если используете локальный CLI)

create table if not exists public.transactions (
  id          bigint generated by default as identity primary key,
  amount      numeric(10, 2) not null check (amount > 0),
  type        text           not null check (type in ('income', 'expense')),
  category    text           not null,
  description text,
  date        date           not null,
  created_at  timestamptz    not null default now()
);

create index if not exists transactions_date_idx on public.transactions (date desc);

-- Row Level Security: учебный проект без авторизации.
-- В Модуле 7 эти политики заменим на auth.uid() = user_id.
alter table public.transactions enable row level security;

drop policy if exists "transactions_select_all" on public.transactions;
drop policy if exists "transactions_insert_all" on public.transactions;
drop policy if exists "transactions_update_all" on public.transactions;
drop policy if exists "transactions_delete_all" on public.transactions;

create policy "transactions_select_all"
  on public.transactions for select using (true);

create policy "transactions_insert_all"
  on public.transactions for insert with check (true);

create policy "transactions_update_all"
  on public.transactions for update using (true) with check (true);

create policy "transactions_delete_all"
  on public.transactions for delete using (true);

-- Тестовые данные (5 строк)
insert into public.transactions (amount, type, category, description, date) values
  (65000.00, 'income',  'Зарплата',    'Зарплата за месяц',   current_date - 5),
  (12000.00, 'income',  'Фриланс',     'Подработка',           current_date - 3),
  ( 4500.00, 'expense', 'Еда',         'Продукты на неделю',   current_date - 2),
  ( 1800.00, 'expense', 'Транспорт',   'Метро + такси',        current_date - 1),
  ( 3200.00, 'expense', 'Развлечения', 'Кино и кафе',          current_date);
