-- Модуль: мультивалютность, курсы НБ РБ, кошельки
-- Supabase Studio → SQL Editor → Run
--
-- Если ещё не выполняли 0002_auth_user_id_rls.sql — ниже он встроен.
-- Нужен хотя бы один пользователь в Authentication (зарегистрируйтесь в приложении).

-- === Встроенная миграция 0002 (user_id + RLS), если колонки ещё нет ===
alter table public.transactions
  add column if not exists user_id uuid references auth.users (id) on delete cascade;

delete from public.transactions where user_id is null;

do $$
begin
  if not exists (
    select 1
    from information_schema.columns c
    where c.table_schema = 'public'
      and c.table_name = 'transactions'
      and c.column_name = 'user_id'
      and c.is_nullable = 'YES'
  ) then
    null;
  else
    alter table public.transactions alter column user_id set not null;
  end if;
exception
  when others then
    raise notice 'user_id: %', sqlerrm;
end $$;

create index if not exists transactions_user_id_idx on public.transactions (user_id);
create index if not exists transactions_user_date_idx
  on public.transactions (user_id, date desc);

drop policy if exists "transactions_select_all" on public.transactions;
drop policy if exists "transactions_insert_all" on public.transactions;
drop policy if exists "transactions_update_all" on public.transactions;
drop policy if exists "transactions_delete_all" on public.transactions;

drop policy if exists "transactions_select_own" on public.transactions;
drop policy if exists "transactions_insert_own" on public.transactions;
drop policy if exists "transactions_update_own" on public.transactions;
drop policy if exists "transactions_delete_own" on public.transactions;

create policy "transactions_select_own"
  on public.transactions for select
  using (auth.uid() = user_id);

create policy "transactions_insert_own"
  on public.transactions for insert
  with check (auth.uid() = user_id);

create policy "transactions_update_own"
  on public.transactions for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "transactions_delete_own"
  on public.transactions for delete
  using (auth.uid() = user_id);

-- === Курсы и кошельки (0003) ===

-- Курсы валют (общий кэш, BYN за 1 единицу валюты)
create table if not exists public.exchange_rates (
  currency          text primary key,
  rate_to_byn       numeric(18, 8) not null check (rate_to_byn > 0),
  cur_scale         integer not null default 1 check (cur_scale > 0),
  cur_official_rate numeric(18, 8) not null,
  rate_date         date not null,
  updated_at        timestamptz not null default now()
);

alter table public.exchange_rates enable row level security;

drop policy if exists "exchange_rates_select_authenticated" on public.exchange_rates;
create policy "exchange_rates_select_authenticated"
  on public.exchange_rates for select
  to authenticated
  using (true);

-- Кошельки пользователя
create table if not exists public.wallets (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  currency   text not null,
  balance    numeric(14, 2) not null default 0 check (balance >= 0),
  created_at timestamptz not null default now(),
  unique (user_id, currency),
  check (currency in ('BYN', 'USD', 'EUR', 'RUB', 'KZT'))
);

create index if not exists wallets_user_id_idx on public.wallets (user_id);

alter table public.wallets enable row level security;

drop policy if exists "wallets_select_own" on public.wallets;
drop policy if exists "wallets_insert_own" on public.wallets;
drop policy if exists "wallets_update_own" on public.wallets;

create policy "wallets_select_own"
  on public.wallets for select
  using (auth.uid() = user_id);

create policy "wallets_insert_own"
  on public.wallets for insert
  with check (auth.uid() = user_id);

-- balance меняется только через триггер (security definer), не через клиентский update
create policy "wallets_update_own"
  on public.wallets for update
  using (false);

-- Валюта транзакции
alter table public.transactions
  add column if not exists currency text not null default 'BYN';

alter table public.transactions
  drop constraint if exists transactions_currency_check;

alter table public.transactions
  add constraint transactions_currency_check
  check (currency in ('BYN', 'USD', 'EUR', 'RUB', 'KZT'));

-- Синхронизация кошелька при изменении транзакций
create or replace function public.ensure_wallet_row(p_user_id uuid, p_currency text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.wallets (user_id, currency, balance)
  values (p_user_id, p_currency, 0)
  on conflict (user_id, currency) do nothing;
end;
$$;

create or replace function public.apply_wallet_delta(
  p_user_id uuid,
  p_currency text,
  p_delta numeric
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  new_balance numeric;
begin
  perform public.ensure_wallet_row(p_user_id, p_currency);

  update public.wallets
  set balance = balance + p_delta
  where user_id = p_user_id and currency = p_currency
  returning balance into new_balance;

  if new_balance < 0 then
    raise exception 'insufficient_wallet_funds'
      using errcode = 'P0001',
            message = 'Недостаточно средств в кошельке';
  end if;
end;
$$;

create or replace function public.transaction_wallet_delta(
  p_type text,
  p_amount numeric
)
returns numeric
language sql
immutable
as $$
  select case when p_type = 'income' then p_amount else -p_amount end;
$$;

create or replace function public.sync_transaction_wallet()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.apply_wallet_delta(
      new.user_id,
      new.currency,
      public.transaction_wallet_delta(new.type, new.amount)
    );
    return new;
  elsif tg_op = 'DELETE' then
    perform public.apply_wallet_delta(
      old.user_id,
      old.currency,
      -public.transaction_wallet_delta(old.type, old.amount)
    );
    return old;
  elsif tg_op = 'UPDATE' then
    perform public.apply_wallet_delta(
      old.user_id,
      old.currency,
      -public.transaction_wallet_delta(old.type, old.amount)
    );
    perform public.apply_wallet_delta(
      new.user_id,
      new.currency,
      public.transaction_wallet_delta(new.type, new.amount)
    );
    return new;
  end if;
  return null;
end;
$$;

drop trigger if exists transactions_wallet_sync on public.transactions;
create trigger transactions_wallet_sync
  after insert or update or delete on public.transactions
  for each row
  execute function public.sync_transaction_wallet();

-- Инициализация кошельков из существующих транзакций (только где есть user_id)
insert into public.wallets (user_id, currency, balance)
select
  t.user_id,
  coalesce(t.currency, 'BYN'),
  greatest(
    0,
    coalesce(
      sum(
        case
          when t.type = 'income' then t.amount
          else -t.amount
        end
      ),
      0
    )
  )
from public.transactions t
where t.user_id is not null
group by t.user_id, coalesce(t.currency, 'BYN')
on conflict (user_id, currency) do update
set balance = excluded.balance;
